### PR TITLE
add jwt_key

### PR DESCRIPTION
**Pull request by c0ze**
related to #12

### CODE REVIEW

**Comment by kunihiko-t** [comment]
It works fine 👍 

What do you think display token with curl command?
Like `-H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MDgwNTcwNTEsImlhdCI6MTUwODA1MzQ1MX0.3c_xUaleCdHy_fdU9zFB50j3hqwYWgPZ-EkTXV3VWag'`

**Comment by c0ze** [comment]
yeah that's a good idea !

**Comment by c0ze** [comment]
@kunihiko-t ok added, can you have another look ? Thanks !

**Comment by c0ze** [comment]
rebased to master, now builds successfully

**Pull request merged**
